Master java 15108 (#13144)
* Added server.servlet.register-default-servlet=true

to application.properties file to eliminate
java.lang.IllegalStateException: Unable to locate the default servlet
for serving static content. error

* Changed mysql-connector name space

to eliminate warning message The artifact
mysql:mysql-connector-java:jar:8.0.31 has been relocated to
com.mysql:mysql-connector-j:jar:8.0.31

* Fixed test givenDisabledSecurityExpression_whenGetFooByName_thenError()

Removed second assert, because "java.lang.RuntimeException: method
hasAuthority() not allowed" is seen in console but is not passed to
testing. Test returns "Internal Server Error"

* Removed location changes I previously made to mysql-connector-java in
the pom

Co-authored-by: tverk <tverk@TomsXPS17-9720.attlocal.net>
Former-commit-id: 590b1713e3a4896e1d6540c12a0b8bac8cf7987f